name: Snyk Infrastructure as Code
on: pull_request
jobs:
  snyk:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk IaC Scanning
        uses: docker://snyk/snyk:alpine
        with:
          args: snyk iac test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.PLATFORM_SNYK_TOKEN }}
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
